 -  Write a function so that the columns of the output matrix are powers of the input
    vector.
    The order of the powers is determined by the increasing boolean argument. Specifically, when
    increasing is False, the i-th output column is the input vector raised element-wise to the power
    of N - i - 1.
    HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
    Theophile Vandermonde.

In [1]:
import numpy as np
import pandas as pd

In [2]:
def ATV(vect, N, increasing):
    mat=np.array(vect).T
    mat1=mat**0
    print(mat)
    if increasing== True:
        
        for i in range(1,N):
            mat1=np.column_stack((mat1,mat**i))
    else:
        for i in range(1,N):
            
            mat1=np.column_stack((mat**i,mat1))

        
    print(mat1)     

In [3]:
ATV([1,2,3],3,False)

[1 2 3]
[[1 1 1]
 [4 2 1]
 [9 3 1]]


### kth moving average

In [4]:
def moving_average(sequence, k):
    N=len(sequence) -k+1
    sequence=np.array(sequence)
    result=np.zeros(N)

    for i in range(N):
        for j in range(i,i+k):
            result[i]=result[i] +sequence[j]
        result[i]=result[i]/(k)    
    print(result)


In [5]:
moving_average([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150], 3)

[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]
